apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: urbanmart

spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service

    spec:
      containers:
        - name: user-service
          image: asia-south1-docker.pkg.dev/urban-mart-497808/urban-mart-microservices-images/user-service:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8088

          env:
            - name: SPRING_APPLICATION_NAME
              value: "USER-SERVICE"

            - name: SERVER_PORT
              value: "8088"

            - name: SPRING_DATASOURCE_URL
              value: DB_USERNAME_URL

            - name: SPRING_DATASOURCE_USERNAME
              value: DB_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              value: DB_PASSWORD

            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET

            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"

          resources:
            requests:
              memory: "250Mi"
              cpu: "100m"

            limits:
              memory: "512Mi"
              cpu: "250m"